import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { DfnsConnectProvider } from "@dfns/sdk-connect/sdk-connect/DfnsConnectProvider";
import "./globals.css";
import { PropsWithChildren, ReactElement } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DfnsConnectProvider>{children}</DfnsConnectProvider>
      </body>
    </html>
  );
}