import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { DfnsConnectProvider } from "@dfns/sdk-connect/sdk-connect/DfnsConnectProvider";
import { DfnsConnectConfig } from "../../../sdk-connect";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dfnsConnectConfig: DfnsConnectConfig = {
  iframeUrl: "http://localhost:3000/iframe",
  appId: "ap-6e1fi-nklmr-9ona9pupmq9h4s75",
  orgId: "or-yanke-mars-6ulofamogg84s87v",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DfnsConnectProvider config={dfnsConnectConfig}>
          {children}
        </DfnsConnectProvider>
      </body>
    </html>
  );
}
