import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { DfnsConnectProvider } from "@dfns/sdk-connect/sdk-connect/DfnsConnectProvider";
import { DfnsConnectConfig } from "../../../sdk-connect";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dfnsConnectConfig: DfnsConnectConfig = {
  iframeUrl: "http://localhost:3000/iframe",
  appId: "ap-6e1fi-nklmr-9ona9pupmq9h4s75",
  orgId: "or-yanke-mars-6ulofamogg84s87v",
};

// NEXT_PUBLIC_IFRAME_URL=http://localhost:3000/iframe
// # NEXT_PUBLIC_IFRAME_URL='https://app.dfns.wtf/iframe'
// NEXT_PUBLIC_IFRAME_ORIGIN=http://localhost:3000
// NEXT_PUBLIC_DFNS_APP_ID=ap-6e1fi-nklmr-9ona9pupmq9h4s75
// NEXT_PUBLIC_DFNS_ORG_ID=or-yanke-mars-6ulofamogg84s87v
// DFNS_API_URL='https://api.dfns.wtf'
// DFNS_PRIVATE_KEY='-----BEGIN EC PRIVATE KEY-----
// MHcCAQEEINTefVAPDHfffXzbcjFDLwEdV04TOu1l/TFW+te9/8H9oAoGCCqGSM49
// AwEHoUQDQgAE6ncQIumIzlNscfpHz/7AkfP4W68ClLZRU3Bu522ih9NHDJsBtZlU
// 0yW2Zvm6eIhYaCC3bEsPl9S07bq0Cq8p4w==
// -----END EC PRIVATE KEY-----'
// # service account dfnsconnect-wtf-2
// DFNS_CRED_ID=Y2ktNHZqcXMtc2NxN28tOXJhcGZwOW1oOTVscmpvNg
// DFNS_AUTH_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSJ9.eyJpc3MiOiJhdXRoLmRmbnMud3RmIiwiYXVkIjoiZGZuczphdXRoOnVzZXIiLCJzdWIiOiJvci15YW5rZS1tYXJzLTZ1bG9mYW1vZ2c4NHM4N3YiLCJqdGkiOiJ0by0zdG05Mi1zNG44aS05Z3ByYW4zdnZrZTVvMTRnIiwic2NvcGUiOiIiLCJwZXJtaXNzaW9ucyI6W10sImh0dHBzOi8vY3VzdG9tL3VzZXJuYW1lIjoiZGZuc2Nvbm5lY3Qtd3RmLTIiLCJodHRwczovL2N1c3RvbS9hcHBfbWV0YWRhdGEiOnsidXNlcklkIjoidXMtbXNyNzEtMnNjdTktOXZiNTlnaXU0ZnRrYnFxIiwib3JnSWQiOiJvci15YW5rZS1tYXJzLTZ1bG9mYW1vZ2c4NHM4N3YiLCJ0b2tlbktpbmQiOiJTZXJ2aWNlQWNjb3VudCJ9LCJpYXQiOjE3MTU2MDYwNjUsImV4cCI6MTc3ODY3ODA2NX0.Q0rioxoeOa3kiyOCQKW95csBHN097MfyADMu0wITmtMKb06fl46nuaIRvbIiSbqZAq-rn2UySw3VZruvQswfCA

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DfnsConnectProvider config={dfnsConnectConfig}>
          {children}
        </DfnsConnectProvider>
      </body>
    </html>
  );
}
